plugins {
    id("org.jetbrains.kotlin.jvm") version "1.9.25" apply(false)
    id("org.jetbrains.kotlin.plugin.spring") version "1.9.25" apply(false)
    id("org.jlleitschuh.gradle.ktlint") version "12.1.2" apply(false)
    id("org.springframework.boot") version "3.4.3" apply(false)
    id("io.spring.dependency-management") version "1.1.7" apply(false)
    id("org.jooq.jooq-codegen-gradle") version "3.19.20" apply(false)
    id("org.flywaydb.flyway") version "11.3.3" apply(false)
}

allprojects {
    group = "com.demo.project.librarystore"
    version = "0.0.1-SNAPSHOT"
}

subprojects {
    repositories {
        mavenCentral()
    }
    apply {
        plugin("org.jetbrains.kotlin.jvm")
        plugin("org.jlleitschuh.gradle.ktlint")
    }
    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }
    ktlint {
        version = "1.5.0"
        verbose = true
    }
    kotlin {
        compilerOptions {
            freeCompilerArgs.add("-Xjsr305=strict")
        }
    }
    tasks.named("test") {
        useJUnitPlatform()
    }
}