apply {
    plugin("org.springframework.boot")
    plugin("io.spring.dependency-management")
    plugin("org.jetbrains.kotlin.plugin.spring")
}

configurations {
    mockitoAgent
}

dependencies {
    implementation project(":database")

    implementation "org.springframework.boot:spring-boot-starter-jooq"
    implementation "org.springframework.boot:spring-boot-starter-web"
    implementation "com.fasterxml.jackson.module:jackson-module-kotlin"
    implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.5"
    implementation "jakarta.validation:jakarta.validation-api"
    implementation "org.hibernate.validator:hibernate-validator"
    runtimeOnly "org.postgresql:postgresql"
    compileOnly "org.projectlombok:lombok"
    annotationProcessor "org.projectlombok:lombok"
    testImplementation "org.springframework.boot:spring-boot-starter-test"
    testImplementation "org.jetbrains.kotlin:kotlin-test-junit5"
    testImplementation "com.h2database:h2"
    testImplementation "org.mockito:mockito-core:5.15.2"
    configurations {
        mockitoAgent("org.mockito:mockito-core:5.15.2") {
            transitive = false
        }
    }
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

tasks {
    test {
        jvmArgs += "-javaagent:${configurations.mockitoAgent.asPath}"
    }
}